services:
  - type: web
    name: scge-backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    repo: https://gitlab.com/platinimichell/scge.git
